version: '3.5'
services:
    db:
        image: postgres:latest
        container_name: postgres
        ports:
            - 5432:5432
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        command: postgres -c 'max_connections=200'
        volumes:
            - user_api_db:/var/lib/postgresql/data
        networks:
            - dev

    user_api:
        build: .
        image: user_api:latest
        container_name: user_api
        ports:
            - 8080:8080
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db
        links:
            - db
        networks:
            - dev
        restart: on-failure
volumes:
    user_api_db:
      name: user_api_db
networks:
    dev:
      name: dev
      driver: bridge
