apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: aly.com
    http:
      paths:
      - backend:
          serviceName: "{{ .Chart.Name }}"
          servicePort: 8080
        path: /